# kill any processes that may be accessing the Realsense camera
# sudo kill -9 $(sudo lsof /dev/video2 -t | sed -n '2p' | awk '{print $2}') 0>/dev/null 1>/dev/null
# echo "Killed all processes accessing Realsense on /dev/video2"


# THIS SCRIPT GENERATED BY o4-mini, USE WITH CAUTION

#!/usr/bin/env bash
set -euo pipefail

echo "==> Killing processes accessing /dev/video2"
# gather PIDs (if any)
video_pids=$(sudo lsof -t /dev/video2 2>/dev/null || true)
if [[ -n "$video_pids" ]]; then
  echo "Found PIDs: $video_pids"
  echo "$video_pids" | xargs sudo kill -9
  echo "Done."
else
  echo "No processes accessing /dev/video2 found."
fi

echo
echo "==> Killing all python3.6 processes"
# gather python3.6 PIDs (if any)
py_pids=$(pgrep -x python3.6 || true)
if [[ -n "$py_pids" ]]; then
  echo "Found python3.6 PIDs: $py_pids"
  echo "$py_pids" | xargs sudo kill -9
  echo "Done."
else
  echo "No python3.6 processes found."
fi
